# Generated by Django 2.2 on 2020-10-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parksystemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkPropertyAvailbility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('property_availability_date', models.DateField()),
                ('property_availability_starttime', models.TimeField()),
                ('property_availability_endtime', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='parkproperty',
            name='park_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop.parkname+', to='parksystemapp.Park'),
        ),
        migrations.AddField(
            model_name='parkpropertyavailbility',
            name='property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ava.propertyname+', to='parksystemapp.ParkProperty'),
        ),
    ]
