# Generated by Django 2.2.13 on 2020-11-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parksystemapp', '0002_auto_20201006_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkPropertyAvailbility',
        ),
    ]
