# Generated by Django 2.2.13 on 2020-12-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parksystemapp', '0003_delete_parkpropertyavailbility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='res_eventdate',
        ),
        migrations.AlterField(
            model_name='parkproperty',
            name='property_slot',
            field=models.CharField(blank=True, default='2 hours', max_length=50, null=True),
        ),
    ]
