# Generated by Django 2.2 on 2020-10-06 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parksystemapp', '0003_propertystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_amount', models.IntegerField(default='')),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transaction_notes', models.TextField(default='')),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans.resid+', to='parksystemapp.Reservation')),
            ],
        ),
    ]
