# Generated by Django 2.2.13 on 2020-12-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parksystemapp', '0005_remove_reservation_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertystatus',
            name='property_name',
        ),
    ]
